chore(PostgreSQL-DB): Configure Authors Haven to use PostgreSQL as DB…
andela/lotus-ah pull request #1
Opened 2018-09-25 12:35 UTC by Mrshinezee

#### What does this PR do?
-Configure the project to use sequelize and postgres

#### Description of Task to be completed?
- Integration of sequelize into the project

#### How should this be manually tested?
- Clone the repo
- cd into the 'lotus-ah'
- Run 'npm install'
- Use the .env.sample format to create a .env file
- Run 'npm run start:dev'

#### What are the relevant pivotal tracker stories?
[#160451587](Configure Authors Haven to use PostgreSQL as DB Engine )

2018-09-25 13:59 UTC, KaiserPhemi requested changes

2018-09-25 13:59 UTC, KaiserPhemi commented on .babelrc
> +}
#### Nitpick
Insert a new line at the end of every file.

2018-09-25 13:59 UTC, KaiserPhemi commented on index.js
> +import express from 'express';
#### Critical
Why do we have this flag ? Please check the configuration file and fix this.

2018-09-25 20:21 UTC, Mrshinezee commented on .babelrc
> +}
Thanks will fix it

2018-09-25 20:59 UTC, Mrshinezee commented on index.js
> +import express from 'express';
I refactored the es5 to es6, I am still trying to figure out why houndci is flagging import

2018-09-27 09:06 UTC, obulaworld approved these changes
Looking good to me

2018-09-27 09:06 UTC, Victor-Ugwueze approved these changes
LGTM

2018-09-27 12:03 UTC, KaiserPhemi approved these changes

2018-09-27 12:06 UTC, merged