Feat user login 160921952
andela/lotus-ah pull request #15
Opened 2018-10-05 12:35 UTC by obulaworld

**What does this PR do?**
-It completes the user login api feature.
**Description of Task to be completed?**
- Complete the user login feature
- Authenticate the user details
**How should this be manually tested?**
Clone the repo
- cd into the 'lotus-ah'
- Run 'npm install'
- Use the .env.sample format to create a .env file
- Run 'npm run migrate'
- Run 'npm run start:dev'
Any background context you want to provide?
None

What are the relevant pivotal tracker stories?
[#160921952](https://www.pivotaltracker.com/story/show/160921952")

2018-10-08 12:05 UTC, Victor-Ugwueze approved these changes
LGTM

2018-10-08 12:06 UTC, Mrshinezee approved these changes
Lgtm

2018-10-08 22:39 UTC, KaiserPhemi requested changes
#### Critical
Rebase and fix merge conflicts

2018-10-09 10:04 UTC, KaiserPhemi approved these changes

2018-10-09 10:09 UTC, merged