feat(reset passwod): reset password via email
andela/lotus-ah pull request #16
Opened 2018-10-05 16:48 UTC by Victor-Ugwueze

#### What does this PR do?
- Reset password via email

#### Description of Task to be completed?
  - add AuthController.js
  - add ```resetPasseord``` and ```forgotPassword``` methods to AuthController
  - add authValidator.js to middleware to verify token from user's request and check the new password validity.
 - add route `/api/auth/forgot_password` and `/api/auth/reset_password`
  

#### How should this be manually tested?
    - Clone the repo
    - cd into the 'lotus-ah'
    - Run 'npm install'
    - Use the .env.sample format to create a .env file
    - Run 'npm run migrate'
    - Run 'npm run start:dev'

#### Any background context you want to provide?
None

#### What are the relevant pivotal tracker stories?
[#160451597](https://www.pivotaltracker.com/story/show/160451597 "reset password")
 
###Question
 NA

2018-10-08 22:43 UTC, KaiserPhemi requested changes
#### Critical
- Implement feedback
- Fix merge conflict

2018-10-08 22:43 UTC, KaiserPhemi commented on server/controllers/AuthController.js
> +      .catch(e => e);
#### Critical
What's `e`? Be more explicit

2018-10-09 00:09 UTC, Victor-Ugwueze commented
I have fixed the conflict. I also changed package manager to yarn,  but I am having import module error.
<img width="1440" alt="screen shot 2018-10-09 at 1 07 30 am" src="https://user-images.githubusercontent.com/24890605/46639725-dcb54900-cb5f-11e8-95da-798d71f64ce5.png">

2018-10-09 00:29 UTC, Victor-Ugwueze commented
I have Implemented the feedback. Please review @KaiserPhemi, thank you.

2018-10-09 04:15 UTC, KaiserPhemi approved these changes

2018-10-09 04:16 UTC, merged