#160451600 Build out REST Endpoints for Article (CRUD)
andela/lotus-ah pull request #18
Opened 2018-10-08 18:43 UTC by mindsworth

#### What does this PR do?
This PR is for the implementation of CRUD functionality for the back-end. It handles the end-points that creates new article, delete article for a specific user, update article for a specific user, get all articles for a specific user, get a single article for a specific user, and get all articles for all users. The PR also covers the testing for the edge cases.

#### Description of Task to be completed?
- implement CRUD functionality on articule
- Wrote test for edge cases

#### How should this be manually tested?
This PR can be tested locally by running the server and using application like postman to make http request to the endpoints.

#### Any background context you want to provide?
None

#### What are the relevant pivotal tracker stories?
` #160451600` Users should be able to create articles

#### Screenshots (if appropriate)
None

#### Questions:
None

2018-10-08 23:11 UTC, KaiserPhemi requested changes

2018-10-08 23:11 UTC, KaiserPhemi commented on tests/emailController.test.js
> +// import chai from 'chai';
#### Critical
Why do we have the entire test file commented out? If it's not needed then delete it but I'll like to know why this is commented out in the first place

2018-10-09 00:42 UTC, KaiserPhemi commented
@mindsworth 
Your PR message is not properly formatted. Please fix this.

2018-10-09 13:37 UTC, KaiserPhemi requested changes
- Implement feedback.

2018-10-09 13:37 UTC, KaiserPhemi commented on server/controllers/ArticleController.js
> +/**
#### Nitpick
Format this properly.

2018-10-09 13:37 UTC, KaiserPhemi commented on server/controllers/ArticleController.js
> +   *
#### Nitpick
Remove this blank line. Also remove other  blank lines in comment blocks

2018-10-09 13:37 UTC, KaiserPhemi commented on server/fixtures/auth.js
> +    // res.status(200).json({ status: 'Success', token, });
#### Nitpick
Remove commented code lines/blocks. If it's not needed, delete it.

2018-10-09 22:27 UTC, KaiserPhemi commented
@mindsworth 
Please fix the Code Coverage. It decreased by 8%

2018-10-10 15:37 UTC, KaiserPhemi approved these changes

2018-10-10 15:41 UTC, Mrshinezee approved these changes
LGTM

2018-10-10 15:43 UTC, merged