#161114862 A user should be able to favourite an article
andela/lotus-ah pull request #20
Opened 2018-10-11 01:42 UTC by Victor-Ugwueze

#### What does this PR do?
- Favourite an article
   
#### Description of Task to be completed?
  - add following methods   to ArticleController   
      - addFavourite   
     - removeFavourite 
     - getAllFavourite

 - add endpoints
    - list all all favourite for user
   ````GET /api/v1/articles/favourites````

   - add article to favourite
   ```` POST /api/v1/articles/:articleId/favourite````

   - remove article from favourite
   ```` DELETE /api/v1/articles/:articleId/favourite````

#### How should this be manually tested?
    - Clone the repo
    - cd into the 'lotus-ah'
    - Run 'npm install'
    - Use the .env.sample format to create a .env file
    - Run 'npm run migrate'
    - Run 'npm run start:dev'

#### Any background context you want to provide?
  It's needed to [this feature](https://www.pivotaltracker.com/story/show/160451607 "send notification feature"). As a user should receive updates on his favourited articles.

#### What are the relevant pivotal tracker stories?
[#161114862](https://www.pivotaltracker.com/story/show/160451597 "reset password")
 
### Question
 NA

### Screenshot
 NA

2018-10-11 03:58 UTC, KaiserPhemi requested changes

2018-10-11 03:58 UTC, KaiserPhemi commented on server/controllers/ArticleController.js
> +    }).then(result => res.status(200).json({ status: 'Success', result }))
#### Can we not make this a one-liner please?
This should read:
```js
.then(result => {
  res.status(200)
      .json({
        status: 'Success',
        result
      })
})
```
This also apply to the next line of code and every where in the code base that this was implemented.

2018-10-11 09:02 UTC, Victor-Ugwueze commented
I have implemented the feedback @KaiserPhemi. Thank you

2018-10-11 11:07 UTC, obulaworld approved these changes
LGTM

2018-10-11 14:02 UTC, KaiserPhemi requested changes

2018-10-11 14:02 UTC, KaiserPhemi commented on server/controllers/ArticleController.js
> +    }).then(result => res.status(200).json({ status: 'Success', result }))
@Victor-Ugwueze 
You did not fix this??!!!

2018-10-11 14:02 UTC, KaiserPhemi commented
@Victor-Ugwueze 
👎

2018-10-11 14:14 UTC, Victor-Ugwueze commented
@KaiserPhemi, Please I am sorry. can look at the screenshot below

<img width="1440" alt="screen shot 2018-10-11 at 3 12 19 pm" src="https://user-images.githubusercontent.com/24890605/46810287-4011c780-cd68-11e8-9430-48fd66100d3d.png">

2018-10-11 15:01 UTC, KaiserPhemi commented
@Victor-Ugwueze 
Please fix merge conflicts.

2018-10-12 12:57 UTC, KaiserPhemi approved these changes

2018-10-12 12:57 UTC, merged