#160451612 View Article reading time
andela/lotus-ah pull request #27
Opened 2018-10-16 10:33 UTC by koiic

#### What does this PR do?
- view reading time of an article
   
#### Description of Task to be completed?
- write a function that calculates the time to read an article

  - add following methods  to ArticleController   
      - timeToRead 
     - add a hook in article model 
         - after creating an article calculate the reading time and assign to article

#### How should this be manually tested?
    - Clone the repo
    - cd into the 'lotus-ah'
    - Run 'npm install'
    - Use the .env.sample format to create a .env file
    - Run 'npm run migrate'
    - Run 'npm run start:dev'

#### Any background context you want to provide?
 NA

#### What are the relevant pivotal tracker stories?
[#160451612](https://www.pivotaltracker.com/story/show/160451616 "calculate reading time")
 
### Question
 NA

### Screenshot
 NA

[Finishes #160451612]"

2018-10-16 20:57 UTC, andela-phemmy approved these changes
Looking Good to Me

2018-10-16 22:14 UTC, KaiserPhemi requested changes
#### Critical
- Fix merge conflicts.

2018-10-17 12:18 UTC, KaiserPhemi commented
@koiic 
- Fix merge conflicts
- Update your PR message on how to test this manually.

2018-10-17 17:52 UTC, KaiserPhemi approved these changes

2018-10-17 17:54 UTC, merged