#160451606 Implement user follow feature
andela/lotus-ah pull request #28
Opened 2018-10-16 20:48 UTC by andela-phemmy

#### What does this PR do?
    This PR create four routes for user follow feature. The routes functionalities are follow,unfollow, list all followers, list all following
#### Description of Task to be completed?
     1. Write test for all 4 routes
     2. Create the routes
     3. Create the controllers
#### How should this be manually tested?
- Start the app locally on port `3000`
- authenticate at least two users
- Construct follow url as follows ```/api/v1/profiles/<followingId>/follow```
- Make a `POST` request to the url
- You should get a response with the structure below:
```js
{
    "profile": {
        "username": null,
        "image": null,
        "bio": null,
        "following": false
    }
}
```
#### Any background context you want to provide?
      Allowing users to follow one another enhances the community mentality.
#### What are the relevant pivotal tracker stories?
      #160451606
#### Screenshots
<img width="1680" alt="screen shot 2018-10-16 at 7 12 45 pm" src="https://user-images.githubusercontent.com/43237059/47046424-f9b7d080-d18c-11e8-9ff8-634a67006f3a.png">
![screen shot 2018-10-16 at 9 12 18 pm 2](https://user-images.githubusercontent.com/43237059/47046425-f9b7d080-d18c-11e8-929c-ee1595e5649d.png)
![screen shot 2018-10-16 at 9 21 40 pm 2](https://user-images.githubusercontent.com/43237059/47046426-fa506700-d18c-11e8-8b3c-e613649b5831.png)
![screen shot 2018-10-16 at 9 21 43 pm 2](https://user-images.githubusercontent.com/43237059/47046427-fa506700-d18c-11e8-8a64-dd4284f2b905.png)
![screen shot 2018-10-16 at 9 21 48 pm 2](https://user-images.githubusercontent.com/43237059/47046430-fa506700-d18c-11e8-9c3b-6a3752b4ca4c.png)
![screen shot 2018-10-16 at 9 22 01 pm 2](https://user-images.githubusercontent.com/43237059/47046431-fae8fd80-d18c-11e8-9da0-084fe699e4df.png)
![screen shot 2018-10-16 at 9 23 14 pm 2](https://user-images.githubusercontent.com/43237059/47046433-fae8fd80-d18c-11e8-9f3e-cf577a1af53c.png)

#### Questions:
   None

2018-10-16 21:06 UTC, Victor-Ugwueze requested changes

2018-10-16 21:06 UTC, Victor-Ugwueze commented on server/controllers/FollowController.js
> +    console.log(followerId);
@andela-phemmy, you forgot to remove some logging statements in line 20 and 21,
please check the file for other occurrences. Thank you.
```
    console.log(followerId);
```

2018-10-16 22:20 UTC, KaiserPhemi requested changes
#### Critical
- Implement Feedback
- Rebase & fix merge conflicts

2018-10-17 12:34 UTC, andela-phemmy commented
@KaiserPhemi  I have implemented the feedback

2018-10-17 13:03 UTC, KaiserPhemi approved these changes

2018-10-17 13:37 UTC, merged