#160451611 Add Search Functionality and Custom filtering based on parameters
andela/lotus-ah pull request #30
Opened 2018-10-18 00:04 UTC by Mrshinezee

#### What does this PR do?
- Implement search functionality
   
#### Description of Task to be completed?
- write tests for endpoints
- search for author
- search for article    
- search for tags

- create endpoints
    - search for author
   `GET /api/v1/search/author/:author`
    - search for article
   `GET /api/v1/search/article/:keyword`
   - search for tag
      ` GET /api/v1/search/tag/:name`

#### How should this be manually tested?

   request  GET /api/v1/search/author/:author
   ```js

response {
    "status": "success",
    "message": "All Author available",
    "Authors": [
        {
            "id": 1,
            "username": "mark",
            "email": "mark4@gmail.com",
            "bio": "I lov tech",
            "imageUrl": ""
        }
```
 GET /api/v1/search/article/:keyword
request 
```js
{
    "status": "success",
    "message": "All articles available",
    "article": [
        {
            "id": 1,
            "slug": "My-passion-35659ed5-3fa3-4cfc-a0e3-e4cb361d5e7b",
            "title": "My passion",
            "description": "Tip to become a better programmer",
            "userId": 1,
            "users": {
                "id": 1,
                "username": "shinezee",
                "email": "shinezee54@gmail.com",
                "bio": "I lov tech",
                "imageUrl": ""
            }
        }
    ]
}
```

GET /api/v1/search/tag/:name
request 

```js
response
{
    "status": "success",
    "message": "Tags successfully obtained",
    "tag": [
        {
            "id": 2,
            "name": "passion",
            "createdAt": "2018-10-17T22:52:47.336Z",
            "updatedAt": "2018-10-17T22:52:47.336Z"
        }
    ]
}
```
#### Any background context you want to provide?
 NA

#### What are the relevant pivotal tracker stories?
[#160451616](https://www.pivotaltracker.com/story/show/160451611 "Add Search Functionality and Custom filtering based on parameters")
 
### Question
 NA

### Screenshot
 NA

2018-10-18 14:56 UTC, KaiserPhemi requested changes
#### Nitpick
- Rebase and fix merge conflicts

2018-10-19 13:29 UTC, Victor-Ugwueze approved these changes
LGTM

2018-10-19 13:30 UTC, obulaworld approved these changes
LGTM

2018-10-19 13:49 UTC, KaiserPhemi approved these changes

2018-10-19 13:50 UTC, merged